#!/usr/bin/env node
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'fs';
import { resolve, dirname, basename, extname, join } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const summernoteNextRoot = resolve(__dirname, '..');

function listSvgs(svgDir) {
  if (!existsSync(svgDir)) {
    return [];
  }
  return readdirSync(svgDir)
    .filter((file) => file.endsWith('.svg'))
    .sort();
}

function writeManifest(svgDir, outFile) {
  const files = listSvgs(svgDir);
  const body = [
    '// AUTO-GENERATED by scripts/build-icons.js. Do not edit by hand.',
    '// Lists every icon glyph that can be fetched from icons/<name>.svg.',
    'const ICONS = [',
    ...files.map((file) => `  ${JSON.stringify(basename(file, extname(file)))},`),
    '];',
    '',
    'export default ICONS;',
    'export const ICON_COUNT = ICONS.length;',
    '',
  ].join('\n');
  writeFileSync(outFile, body);
  return files.length;
}

function copySvgs(srcDir, destDir) {
  if (!existsSync(srcDir)) {
    return 0;
  }
  mkdirSync(destDir, { recursive: true });
  const files = listSvgs(srcDir);
  for (const file of files) {
    const src = join(srcDir, file);
    const dest = join(destDir, file);
    const content = readFileSync(src, 'utf-8');
    writeFileSync(dest, content);
  }
  return files.length;
}

export { writeManifest, copySvgs };

function main() {
  const start = Date.now();
  const srcRoot = resolve(summernoteNextRoot, 'src');
  const svgDir = join(srcRoot, 'icons');
  const manifestOut = resolve(srcRoot, 'js', 'icons.js');

  if (!existsSync(svgDir)) {
    throw new Error(`Missing SVG directory: ${svgDir}`);
  }

  console.log(`Generating icon manifest: ${svgDir} -> ${manifestOut}`);
  const count = writeManifest(svgDir, manifestOut);
  console.log(`Wrote manifest with ${count} icon name(s).`);

  const elapsed = ((Date.now() - start) / 1000).toFixed(2);
  console.log(`Done in ${elapsed}s.`);
}

main();