import { build } from 'vite';
import { pathToFileURL } from 'url';
import { readdirSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { configs, styles } from '../vite.config.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const iconsDir = resolve(__dirname, '..', 'src', 'font', 'icons');
const manifestPath = resolve(iconsDir, 'index.js');

function writeIconManifest() {
  const names = readdirSync(iconsDir)
    .filter((file) => file.endsWith('.svg'))
    .map((file) => file.replace(/\.svg$/, ''))
    .sort();
  const body = [
    '// AUTO-GENERATED by scripts/build-dist.js. Do not edit by hand.',
    '// Lists every icon glyph that can be lazily fetched from font/icons/<name>.svg.',
    'export default [',
    ...names.map((name) => `  '${name}',`),
    '];',
    '',
  ].join('\n');
  writeFileSync(manifestPath, body);
  return names;
}

function copyIconAssets(outDir) {
  const destDir = resolve(outDir, 'font', 'icons');
  mkdirSync(destDir, { recursive: true });
  const svgFiles = readdirSync(iconsDir).filter((file) => file.endsWith('.svg'));
  for (const file of svgFiles) {
    copyFileSync(resolve(iconsDir, file), resolve(destDir, file));
  }
  return svgFiles.length;
}

async function buildVariant(config, fileBase, emptyOutDir) {
  const minifiedConfig = {
    ...config,
    build: {
      ...config.build,
      emptyOutDir,
      minify: true,
      terserOptions: undefined,
      lib: {
        ...config.build.lib,
        fileName: () => `${fileBase}.min.js`,
      },
      rollupOptions: {
        ...config.build.rollupOptions,
        output: {
          ...config.build.rollupOptions.output,
          assetFileNames: `${fileBase}.min.[ext]`,
          entryFileNames: `${fileBase}.min.js`,
        },
      },
    },
  };

  const unminifiedConfig = {
    ...config,
    build: {
      ...config.build,
      emptyOutDir: false,
      minify: false,
      terserOptions: { compress: false, mangle: false },
      lib: {
        ...config.build.lib,
        fileName: () => `${fileBase}.js`,
      },
      rollupOptions: {
        ...config.build.rollupOptions,
        output: {
          ...config.build.rollupOptions.output,
          assetFileNames: `${fileBase}.[ext]`,
          entryFileNames: `${fileBase}.js`,
        },
      },
    },
  };

  await build(minifiedConfig);
  await build(unminifiedConfig);
}

export async function buildDist() {
  let emptyOutDir = true;

  writeIconManifest();

  for (const [style, config] of Object.entries(configs)) {
    await buildVariant(config, styles[style].fileBase, emptyOutDir);
    emptyOutDir = false;
  }

  const distDir = resolve(__dirname, '..', 'dist');
  if (existsSync(distDir)) {
    copyIconAssets(distDir);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await buildDist();
}